### ISSUE TITLE
Unable to load DLL 'lib/libxgboost.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by PicNet** [PicNet/XGBoost.Net#2]
NuGet package failing with the following exception:

System.DllNotFoundException: Unable to load DLL 'lib/libxgboost.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
    at XGBoost.XGBOOST_NATIVE_METHODS.XGDMatrixCreateFromMat(Single[] data, UInt64 nrow, UInt64 ncol, Single missing, IntPtr& handle)
   at XGBoost.DMatrix..ctor(Single[][] data, Single[] labels)
   at XGBoost.XGBClassifier.Fit(Single[][] data, Single[] labels)
   at TestXGBoost.UnitTest1.TestMethod1() in c:\dev\projects\test_xgb\TestXGBoost\TestXGBoost\UnitTest1.cs:line 18

This is in a 64 bit MSTest project.

**Comment by cycloidistic** [comment]
Ok. Should be fixed now. Use the PicNet.XGBoost NuGet package version 0.0.7 and above.

**Comment by ZHmaper** [comment]
NuGet version 5.10.0.7240 still meet this problem.

**Comment by ZHmaper** [comment]
The version 0.2.0 and version 0.2.2 meet this problem again.
